### ISSUE TITLE
"Start Minimized" fucation can,t work

### ISSUE THREAD

**Issue by hehehe5567** [DaniGTA/CloudFlare-DDNS-Updater#1]
"CloudFlare-DDNS-Auto-Update.2.1.exe" this is very useful to me, thank you for sharing.

In settings, I have chosen to start minimizing, but every time I reopen the program, it will be start GUI.

**Comment by DaniGTA** [comment]
i fixed, do you want a .exe or do you want too build it on your own ?

**Comment by hehehe5567** [comment]
Thank you for your response, if possible, I hope you can upload .exe, thanks

**Comment by DaniGTA** [comment]
https://github.com/DaniGTA/CloudFlare-DDNS-Updater/releases/tag/v2.1.1
