### ISSUE TITLE
I get an unhandled exception error when pasting in my API code.

### ISSUE THREAD

**Issue by bnosie** [DaniGTA/CloudFlare-DDNS-Updater#2]
Windows 10.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CloudFlareDDNS.frmSettings.<>c__DisplayClass2_0.<load_Zones>b__0()

**Comment by DaniGTA** [comment]
Can it be that you dont have any websites on your cloudflare acc ?

**Comment by bnosie** [comment]
i do have a website on it.  I have been using birkett's updater, and need to update due to the api version issue.

**Comment by bnosie** [comment]
It happens immediately upon pasting the code.

**Comment by DaniGTA** [comment]
The thing is it cant crash cuse it should be catched, thats why i cant reproduce it, i hope you use the newest version and have the right https://www.microsoft.com/en-us/download/details.aspx?id=48130 

i can try a workaround problably it can fix your problem

**Comment by DaniGTA** [comment]
https://github.com/DaniGTA/CloudFlare-DDNS-Updater/releases/tag/v2.1.2_Test test this pls

**Comment by bnosie** [comment]
That one works, thanks!  
FYI, I tried v2.1.1 on a Windows 2008R2 server and got the same error as well.
