### ISSUE TITLE
Not saving settings on restart

### ISSUE THREAD

**Issue by 615283** [DaniGTA/CloudFlare-DDNS-Updater#5]
When my server restarts, I have to manually re enter my settings. Running server 2012 R2.

**Comment by DaniGTA** [comment]
Make sure that CloudFlareDDNS.exe can write to CloudFlareDDNS.exe.config . You can see the changes in the config when it work without problems.

**Comment by DaniGTA** [comment]
C:\Users\<YOURACCNAME>\AppData\Roaming\CloudFlareDDNS\user.config

**Comment by 615283** [comment]
I think this is fixed, I was running from the wrong folder.
