### ISSUE TITLE
Not usable with multiple domains

### ISSUE THREAD

**Issue by jamesxsc** [DaniGTA/CloudFlare-DDNS-Updater#7]
Am trying to use several domains however it only shows one domain n the list so I can't tick the other domains' records.

**Comment by DaniGTA** [comment]
Did you mean the domains(zones) in the settings ?

**Comment by jamesxsc** [comment]
I mean the list of records.

**Comment by jamesxsc** [comment]
https://i.615283.net/u/6da49c.png See those domains all selected but only the d-size.com shows up.

**Comment by DaniGTA** [comment]
Test this pls.
[CloudFlareDDNS.zip](https://github.com/DaniGTA/CloudFlare-DDNS-Updater/files/2776825/CloudFlareDDNS.zip)

**Comment by jamesxsc** [comment]
That's working. Marking as solved, presumably you'll push those changes to master.
