### ISSUE TITLE
Minimize & Autostart

### ISSUE THREAD

**Issue by fmohican** [DaniGTA/CloudFlare-DDNS-Updater#8]
Button minimize not work, the window persist on `alt + tab` and `win + tab`, also AutoStart and `/install` isn't work. They throw "Exception Dump"

![image](https://user-images.githubusercontent.com/8583317/62424158-93784c00-b6d3-11e9-8281-4fc817d95156.png)

**Comment by DaniGTA** [comment]
/install will not work because it need a rework in the service structur. But the alt + tab is fixed in v2.1.6 pls test it out.

**Comment by fmohican** [comment]
Sure, i will try out, i will come back with edit a.s.a.p.
